### ISSUE TITLE
Clarity over pricing/availability?

### ISSUE THREAD

**Issue by andybak** [Placeholder-Software/wasmbox#1]
Here's the first time visitor experience:

1. Search for "wasm unity". Find this repo.
2. Nice! Looks useful. I'll download the repo and then read the docs
3. "How do I get it". OK.
4. Wait... 75 euros? So what all that code in the repo?

At this point I've got no idea what the repo does but I have to assume this is a paid product. Could you edit the repo description to make it clear that there's no functionality without buying a paid product?

**Comment by martindevans** [comment]
Sorry about the confusion. The code in this repository is just for the documentation website itself. I'll see if I can expand the readme shown on this repo to clarify the situation better.

Thanks very much for the feedback. This kind of genuine user experience feedback is always really valuable!

**Comment by martindevans** [comment]
I've updated the readme, hopefully that clears up any confusion. I'll close this issue, but feel free to re-open it if you feel anything is still unclear.

**Comment by andybak** [comment]
It's better but I still think I would have missed it. ( I tend to skim readme as do most people)

The fundemental issue the repo name itself. Short of changing that or putting bold red text at the top of the readme, I don't think I'll be the last person to feel slightly misled. I do understand that may or may not be a great concern for you.

**Comment by martindevans** [comment]
I'll try to make it more obvious. The last thing we want is to be confusing people interested in Wasmbox!

**Comment by martindevans** [comment]
Ok I've updated it again, this time the warning is nearer the top. I think that's about as good as it's going to get.

Unfortunately I don't think renaming the repo is possible at this point. It would break too many links.
